spring:
  application:
    # 应用名称，一般就是项目名称，这个名称在SpringCloud中比较关键
    name: MyApplication
  profiles:
    active: dev #指定当前的活动配置文件，主要用于多环境多配置文件的应用中
  thymeleaf:
    prefix: classpath:/pages/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
  mvc:
    favicon:
      enabled: false
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    config:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100Mb

server:
  tomcat:
    uri-encoding: UTF-8
  port: 9090

logging:
  config: classpath:logback-spring.xml

log:
  path:
    all: log/app.log
    error: log/error.log

druid:
  url-mappings: /druid/*
  url-patterns: /*
  username: admin
  password: admin
  resetEnable: false
  allow: "127.0.0.1,192.168.128.242"
  deny: "192.168.128.28"
  exclusions: "*.js,*.gif,*.jpg,*.css,/druid/*"

wx:
  appid: wxda0b5a2b182a2def
  secret: aaac8162b12511ccebbd6bc683438bf4

org:
  quartz:
    # 线程调度器实例名
    scheduler:
      instanceName: quartzScheduler
    # 线程池的线程数，即最多3个任务同时跑
    threadPool:
      threadCount: 3
    # 使用内存存储任务和触发器等信息
    jobStore:
      class: org.quartz.simpl.RAMJobStore
