spring.profiles: dev
spring.profiles.include: common

app:
  first:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/db_quick_app?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: org.gjt.mm.mysql.Driver
      filters: stat,wall,log4j
      minIdle: 5
      initialSize: 5
      maxActive: 20
      maxWait: 200
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis: 5000
      useGlobalDataSourceStat: true
  second:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/db_quick_app?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: org.gjt.mm.mysql.Driver
      filters: stat,wall,log4j
      minIdle: 5
      initialSize: 5
      maxActive: 20
      maxWait: 200
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis: 5000
      useGlobalDataSourceStat: true

log:
  path:
    all: log/app.log
    error: log/error.log
  level:
    app: DEBUG
    root: INFO
